- package.json
- src/calendar/month.jsx
- src/calendar/week.jsx
- Upgrade date-fns to v1.0.0 and newer.
- Set range dependency for classnames package.
> Upgrade deps

- README.md
+ NPM version
+ Travis Build status
+ NPM download stat
+ Better Code Hub stat
> Add Github badges to `Readme.md` file

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/issue_template.md
- CHANGELOG.md
- package.json
https://github.com/toptal/simple-react-calendar/issues/50
* Add Github templates (Contribute, issue, PR)
* Add Changelog
> Add github templates and CHANGELOG.md file

- .eslintrc
- .prettierrc
- CHANGELOG.md
- README.md
- package.json
- src/calendar/__specs__/calendar_spec.js
- src/calendar/__specs__/day_spec.js
- src/calendar/__specs__/days_of_week_spec.js
- src/calendar/__specs__/header_button_spec.js
- src/calendar/__specs__/mocks.js
- src/calendar/__specs__/month_header_spec.js
- src/calendar/__specs__/month_spec.js
- src/calendar/__specs__/notice_spec.js
- src/calendar/__specs__/week_spec.js
- src/calendar/_lib/index.js
- src/calendar/calendar.jsx
- src/calendar/day.jsx
- src/calendar/days_of_week.jsx
- src/calendar/header_button.jsx
- src/calendar/month.jsx
- src/calendar/month_header.jsx
- src/calendar/notice.jsx
- src/calendar/week.jsx
- yarn.lock
+ Fix `.eslintrc` syntax
+ Add `prettier` formatting
+ Auto format to existing files
+ Add `prettier` badge to the `Readme.md` file
> Add `prettier` format to the project

- CHANGELOG.md
- README.md
[GithubIssue - 53](https://github.com/toptal/simple-react-calendar/issues/53)
> Fix `README.md` syntax

- .github/workflows/main.workflow
- .github/workflows/prcheck.yml
- package.json
**NOTE:**
>
> in the code.
>
> …
> Add workflow for PR Checks

- .github/workflows/main.workflow
- .github/workflows/prcheck.yml
- commitlint.config.js
- config/_ci/danger/conventionalCommit.js
- dangerfile.js
- package.json
- yarn.lock
_Describe the changes and motivations for the pull request, unless obvious from the title._
- ~[x]~ n/a Verify that all classes affected by the changes have **good** top-level documentation.
- ~[x]~ n/a Verify that new code has been covered with specs (and features if applicable).
- ~[x]~ n/a Verify that a corresponding meaningful changelog entry has been added (`* Add Github pull request template`), for this change if applicable.
- ~[x]~ n/a Get two :+1: from code review.
_Provide additional notes, remarks, links, mention specific people to review,…_
> chore(commitizen): introduce commitizen to standardize commits

- .github/workflows/release.yml
- README.md
- config/_ci/release/_utils/index.js
- config/_ci/release/bump-package-json
- config/_ci/release/prepare-assets
- package.json
- release.config.js
- yarn.lock
**NOTE:**
>
> in the code.
>
> …
> chore(semanticrelease): introduce semantic release

- .github/workflows/release.yml
**NOTE:**
>
> in the code.
>
> …
> fix(release): fix release job

- .github/workflows/release.yml
**NOTE:**
>
> in the code.
>
> …
> fix(release): disable storybook deploy from github actions

- CHANGELOG.md
- package.json
**NOTE:**
>
> in the code.
>
> …
> Release 1.9.1

- CHANGELOG.md
- package.json
**NOTE:**
>
> in the code.
>
> …
> Release 1.9.2

- .circleci/config.yml
**NOTE:**
>
> in the code.
>
> …
> fix(ci): disable storybook deploy to check the whole process

- .circleci/config.yml
**NOTE:**
>
> in the code.
>
> …
> fix(ci): fix github and npm tokens

- .circleci/config.yml
- package.json
- release.config.js
- yarn.lock
**NOTE:**
>
> in the code.
>
> …
> fix(ci): turn on storybook generate

- .circleci/config.yml
**NOTE:**
>
> in the code.
>
> …
> fix(ci): turn off storybook deployment

- package.json
This task covered by the release job
> chore(npm): remove prepare commmand

- README.md
- src/RenderPropsComponents/Day/Day.tsx
- src/calendar/__specs__/week_spec.tsx
- src/calendar/calendar.tsx
- src/calendar/month.tsx
- src/calendar/week.tsx
- src/helper/index.ts
_Describe the changes and motivations for the pull request, unless obvious from the title._
> docs(readme): extend readme and minor improve on types

- src/calendar/stories/index.jsx
**NOTE:**
> non-relevant to the subject of the pull request should be deleted as well. E.g. if task **Review** checklist items
> does not apply, or if "Screenshots" can't be provided, the corresponding checklist items ("Screenshots provided…" and
>
> in the code.
>
>
> PRs should be merged if and only if all pre-merge …
> chore: fix variable type in demo

- package.json
- yarn.lock
**NOTE:**
> non-relevant to the subject of the pull request should be deleted as well. E.g. if task **Review** checklist items
> does not apply, or if "Screenshots" can't be provided, the corresponding checklist items ("Screenshots provided…" and
>
> in the code.
>
>
> PRs should be merged if and only if all pre-merge …
> chore: replace davinci with davinci-syntax

- package.json
- yarn.lock
**NOTE:**
> non-relevant to the subject of the pull request should be deleted as well. E.g. if task **Review** checklist items
> does not apply, or if "Screenshots" can't be provided, the corresponding checklist items ("Screenshots provided…" and
>
> in the code.
>
>
> PRs should be merged if and only if all pre-merge …
> chore: move package.json deps to dev deps

- src/calendar/month.tsx
Fixes #187.
- (n/a) Verify the branch name starts with `NNNN` where `NNNN` is the issue number.
> fix: disabled date click thrown error

- src/calendar/calendar.tsx
This will remove the unsafe warning from React
> fix: remove unsafe warning

- package.json
- src/RenderPropsComponents/Month/Month.tsx
- src/RenderPropsComponents/Week/Week.tsx
- src/calendar/calendar.tsx
- yarn.lock
Update davinci, lint-staged, husky
> fix(dev): update packages and fix commit lint

- .circleci/config.yml
Exclude PR job in case of master branch
> fix(circleci): filter master triggered PR job

- config/webpack.dev.js
- config/webpack.lib.js
**NOTE:**
> non-relevant to the subject of the pull request should be deleted as well. E.g. if task **Review** checklist items
> does not apply, or if "Screenshots" can't be provided, the corresponding checklist items ("Screenshots provided…" and
>
> in the code.
>
>
> PRs should be merged if and only if all pre-merge …
> chore: fix webpack-merge
